{
 "title": "HCL - BarbaraIOT - Puffin Security",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Network Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Monitoring Traffic Bytes and Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(zeek_net_received_bytes_total[$__rate_interval])",
     "legendFormat": "bytes received"
    },
    {
     "expr": "rate(zeek_net_received_packets_total[$__rate_interval])",
     "legendFormat": "packets received"
    },
    {
     "expr": "rate(zeek_net_dropped_packets_total[$__rate_interval])",
     "legendFormat": "packets dropped"
    }
   ]
  },
  {
   "title": "Log Writes per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(zeek_log_stream_writes_total{}[$__interval])",
     "legendFormat": "{{ stream }}"
    }
   ]
  },
  {
   "title": "Event Handler Invocations per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "events/s" } },
   "targets": [
    {
     "expr": "rate(zeek_event_handler_invocations_total[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sessions per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(zeek_total_sessions_total[$__rate_interval])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  { "title": "IDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "IDS Alerts",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{filename=\"/var/zeek/logs/signatures.log\"} |= ``"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{filename=\"/var/zeek/logs/conn.log\"} |= ``"
    }
   ]
  }
 ]
}